name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          submodules: recursive
      - uses: actions/checkout@v4.1.7
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
      - name: Build
        run: |
          mkdir build
          xcodebuild -scheme VoodooSMBus build
      - uses: actions/upload-artifact@v4.3.4
        with:
          name: VoodooSMBus
          path: build
