name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          submodules: recursive
      - name: Get shortsha
        id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})
      - uses: actions/checkout@v4.1.7
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
      - name: Build
        env:
            VOODOOSMBUS_SHA: VoodooSMBus-${{ steps.vars.outputs.sha_short }}
        run: |
          mkdir build
          xcodebuild -scheme VoodooSMBus build CONFIGURATION_BUILD_DIR=build/${VOODOOSMBUS_SHA}
          mv build/${VOODOOSMBUS_SHA}/VoodooSMBus.kext build/${VOODOOSMBUS_SHA}/${VOODOOSMBUS_SHA}.kext
      - uses: actions/upload-artifact@v4.3.4
        with:
          name: VoodooSMBus
          path: build/VoodooSMBus-*
